### ISSUE TITLE
no module NeighborExtractor5

### ISSUE THREAD

**Issue by xingronaldo** [dywu98/CBL-Conditional-Boundary-Loss#3]

**Comment by dywu98** [comment]
Could you please provide more details about this problem？ Like the command you ran and the error information.

**Comment by xingronaldo** [comment]
> Could you please provide more details about this problem？ Like the command you ran and the error information.

作者你好， 感谢回复。我没有运行，结合论文看了一下CBLocr_head.py， 发现没有NeighborExtractor5，应该是固定卷积核的5 × 5 kernel size depthwise convolution layer吧。另外问一下，‘er_loss’中的‘er’是什么意思呢？

**Comment by xingronaldo** [comment]
> > Could you please provide more details about this problem？ Like the command you ran and the error information.
> 
> 作者你好， 感谢回复。我没有运行，结合论文看了一下CBLocr_head.py， 发现没有NeighborExtractor5，应该是固定卷积核的5 × 5 kernel size depthwise convolution layer吧。另外问一下，‘er_loss’中的‘er’是什么意思呢？

作者你好，我已在其他issue中找到NeighborExtractor5。请问‘er_loss’中的‘er’是什么意思呢？

**Comment by dywu98** [comment]
> > > Could you please provide more details about this problem？ Like the command you ran and the error information.
> > 
> > 
> > 作者你好， 感谢回复。我没有运行，结合论文看了一下CBLocr_head.py， 发现没有NeighborExtractor5，应该是固定卷积核的5 × 5 kernel size depthwise convolution layer吧。另外问一下，‘er_loss’中的‘er’是什么意思呢？
> 
> 作者你好，我已在其他issue中找到NeighborExtractor5。请问‘er_loss’中的‘er’是什么意思呢？

er_loss 其实对应的是文章中所指的A2C Loss。er_loss是早期我们做实验时候的一个曾用名，表示Enhanced Representation，即我们认为这个loss可以起到增强pixel representation的作用。但是后来感觉这个名字不直观，后来才换了A2C Loss这个比较直观的名字。因为这段时间一直比较忙所以没怎么维护这个工程，我们之后将会统一代码与文章中的名字，方便大家理解我们的代码。如果有其他问题，欢迎提问。
